export const FETCH_MANIFEST_INFO = 'MA_FETCH_MANIFEST_INFO';
export const TOGGLE_MANIFEST_UPDATE_MODAL = 'MA_TOGGLE_MANIFEST_UPDATE_MODAL';
export const CALCULATE_SUMMARY_DATA = 'MA_CALCULATE_SUMMARY_DATA';
export const SELECT_PROVIDERS = 'MA_SELECT_PROVIDERS';
export const SELECT_DETAILED_DATA = 'MA_SELECT_DETAILED_DATA';
export const START_INVENTORY_BUNDLE = 'MA_START_INVENTORY_BUNDLE';
export const FETCH_BUNDLE_TASK = 'MA_FETCH_BUNDLE_TASK';
export const RESET_DATA_COLLECTION_STATE = 'MA_RESET_DATA_COLLECTION_STATE';

export const MANIFEST_INFO_URL = '/api/red_hat_migration_analytics';
export const INVENTORY_BUNDLE_URL = '/api/red_hat_migration_analytics';
