export const FETCH_MANIFEST_INFO = 'MA_FETCH_MANIFEST_INFO';
export const CALCULATE_SUMMARY_DATA = 'MA_CALCULATE_SUMMARY_DATA';
export const SELECT_PROVIDERS = 'MA_SELECT_PROVIDERS';
export const SELECT_DETAILED_DATA = 'MA_SELECT_DETAILED_DATA';

export const MANIFEST_INFO_URL = '/api/red_hat_migration_analytics';
