:collections:
  :migration_analytics_manifest:
    :description: Migration Analytics Manifest
    :options:
    - :arbitrary_resource_path
    - :collection
    :identifier: migration_analytics_manifest
    :verbs:
    - :get
    :collection_actions:
      :get:
      - :name: read
        :identifier: red_hat_cloud_services